CREATE DATABASE TestDB;
USE TestDB;

CREATE TABLE Table1 (
Var1 INT(3) NOT NULL,
Var2 INT(3) NOT NULL,
Sum INT(3) NULL
);

INSERT INTO Table1 VALUES ( 2, 3, NULL );

CREATE TRIGGER updateSum
BEFORE INSERT
ON Table1
FOR EACH ROW
SET NEW.Sum = NEW.Var1 + New.Var2;

DELIMITER //
CREATE TRIGGER updateCols
AFTER UPDATE
ON Table1
FOR EACH ROW
BEGIN
SET NEW.Var2 = OLD.Var2 + 1;
END //
DELIMITER ;

SELECT * FROM Table1;

INSERT INTO Table1 VALUES ( 4, 1, NULL );
INSERT INTO Table1 VALUES ( 7, 3, NULL );

UPDATE TABLE Table1 SET Var1 = 6 WHERE Var1 = 7;

SELECT * FROM Table1;


DROP DATABASE TestDB;

quit

